# -*- coding: utf-8 -*-
"""Generating distributions in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6nycXEiosnXrf2NZxSEwWxN143RuvPs
"""

#Binomial distribution:
import numpy as np
import matplotlib.pyplot as plt
n=20
p=0.3
nsim=10000
x=np.random.binomial(n=n,p=p,size=nsim)
print("Mean:",np.mean(x),"Theoretical:",n*p)
print("Var",np.var(x),"Theoretical:",n*p*(1-p))
values,counts=np.unique(x,return_counts=True)
props=counts/nsim
plt.bar(values,props,label="Simulated")
#Theoretical pmf
from scipy.stats import binom
k=np.arange(0,n+1)
plt.plot(k,binom.pmf(k,n,p))
plt.title("Simulated vs Theoretical Binomial")
plt.xlabel("k")
plt.ylabel("Probability")
plt.legend()
plt.show()

#Poisson Distribution
import numpy as np
import matplotlib.pyplot as plt
nsim=10000
lam=5
x=np.random.poisson(lam=lam,size=nsim)
print ("Poisson Mean:",np.mean(x),"Theorestial:",lam)
print("Poisson Var:",np.var(x),"Theoretical:",lam)
values,counts=np.unique(x,return_counts=True)
props=counts/nsim
plt.bar(values,props,label="Simulated")
#Theoretical distribution
from scipy.stats import poisson
k=np.arange(0,max(values)+1)
plt.plot(k,poisson.pmf(k,lam))
plt.title("SImulate vs Theoretical Poisson")
plt.xlabel("k")
plt.ylabel("Probability")
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
rate=2 # Numpy uses 1/rate
nsim=10000
x=np.random.exponential(scale=1/rate,size=nsim)
print("\nExponential Mean:", np.mean(x), " Theoretical:", 1/rate)
print("Exponential Var:", np.var(x), " Theoretical:", 1/rate**2)
plt.hist(x,bins=50,density=True)
#Theoretical Probability
from scipy.stats import expon
xs=np.linspace(0,max(x),200)
plt.plot(xs,expon.pdf(xs,scale=1/rate))
plt.title("Simulated vs Theoretical Exponential")
plt.xlabel("x")
plt.ylabel("Probability")
plt.legend()
plt.show()