# -*- coding: utf-8 -*-
"""Importance sampling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ilRaGliQrNyQmYjiLtVPMcd5MF2pnIX
"""

#Finding function with minimum variance
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
N=100_000
np.random.seed(42)
def g(x):
  return np.where((x>0)&(x<1),np.exp(-x)/(1+x**2),0.0)

exact_value= 0.524797141419702
x0=np.random.uniform(0,1,N)
h0=g(x0)/1.0
est0=np.mean(h0)
var0=np.var(h0)
x1=np.random.exponential(scale=1.0,size=N)
h1=np.where((x1>0)&(x1<1),1.0/(1+x1**2),0.0)
est1=np.mean(h1)
var1=np.var(h1,ddof=1)
x2 = np.random.standard_cauchy(N)
h2 = np.where((x2 > 0) & (x2 < 1), np.pi * np.exp(-x2), 0.0)
est2, var2 = np.mean(h2), np.var(h2, ddof=1)
u3 = np.random.uniform(0, 1, N)
x3 = -np.log(1 - u3 * (1 - np.exp(-1)))
h3 = (1 - np.exp(-1)) / (1 + x3**2)
est3, var3 = np.mean(h3), np.var(h3, ddof=1)
u4 = np.random.uniform(0, 1, N)
x4 = np.tan(u4 * np.pi / 4)
h4 = (np.pi / 4) * np.exp(-x4)
est4, var4 = np.mean(h4), np.var(h4, ddof=1)
print(f"Exact Value: {exact_value:.6f}\n")
results = [
    ("f0 (Uniform)", est0, var0),
    ("f1 (Exponential)", est1, var1),
    ("f2 (Cauchy)", est2, var2),
    ("f3 (Truncated Exp)", est3, var3),
    ("f4 (Truncated Cauchy)", est4, var4),
]
print(f"{'Density Function':<22} | {'Estimate':<10} | {'Variance':<10}")
min_var = float('inf')
best_func = None

for name, est, var in results:
    print(f"{name:<22} | {est:<10.6f} | {var:<10.6f}")
    if var < min_var:
        min_var = var
        best_func = name

print("Function with minimum variance is", best_func)

#Finding the best function in a family of functions
import numpy as np
import matplotlib.pyplot as plt

# Parameters
n = 1000
lambdas = [1, 2, 3, 4]

standard_errors = []

# Same seed for reproducibility
np.random.seed(123)

for lam in lambdas:

    # Generate U ~ Uniform(0,1)
    U = np.random.uniform(0, 1, n)

    # Generate X
    X = 10 - (1 / lam) * np.log(U)

    # Importance sampling ratio
    ratio = (X / lam) * np.exp((lam - 1) * X - 10 * lam)

    # Standard error
    SE = np.std(ratio, ddof=1) / np.sqrt(n)

    standard_errors.append(SE)

# Print values
for lam, se in zip(lambdas, standard_errors):
    print(f"Lambda = {lam}, Standard Error = {se:.8f}")

# Plot
plt.figure(figsize=(8, 5))
plt.plot(lambdas, standard_errors, marker='o')

plt.xlabel("Lambda (λ)")
plt.ylabel("Standard Error")
plt.title("Standard Error vs Lambda")
plt.xticks(lambdas)
plt.grid(True)

plt.show()

