# -*- coding: utf-8 -*-
"""Monte Carlo Testing of Hypothesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13reGDwncdeuEuFdXSGGWGGlNNgffWwwu
"""

#Calculating Type I error rate
import numpy as np
from scipy import stats
mu_0 = 500
sigma=100
n=20
alpha=0.05
num_simulations=100000
np.random.seed(42)
df=n-1
t_crit=stats.t.ppf(1-alpha,df)
samples=np.random.normal(loc=mu_0,scale=sigma,size=(num_simulations,n))
x_bar =np.mean(samples,axis=1)
s=np.std(samples,axis=1,ddof=1)
t_star=(x_bar-mu_0)/(s/np.sqrt(n))
rejections=t_star>t_crit
empirical_type_i_error_rate=np.mean(rejections)
print(f"Empirical Type I Error Rate: {empirical_type_i_error_rate}")
print("Theoretical Alpha: 0.05")

#Checking for mean
import numpy as np
from scipy import stats

n, alpha, mu0, sigma, m = 20, 0.05, 500, 100, 10000
p_vals = np.empty(m)

for j in range(m):
    x = np.random.normal(mu0, sigma, n)
    tstat = (x.mean() - mu0) / (x.std(ddof=1) / np.sqrt(n))
    p_vals[j] = 1 - stats.t.cdf(tstat, df=n - 1)

p_hat = np.mean(p_vals < alpha)
se_hat = np.sqrt(p_hat * (1 - p_hat) / m)
print(f"p value = {p_hat}")
print(f"standard error ={se_hat}")

#Checking for variance
import numpy as np
from scipy import stats

n, alpha, sigma0_sq, m = 20, 0.05, 4, 10000
rej = np.empty(m)

for j in range(m):
    x = np.random.normal(0, np.sqrt(sigma0_sq), n)
    V = (n - 1) * x.var(ddof=1) / sigma0_sq
    rej[j] = V > stats.chi2.ppf(1 - alpha, df=n - 1)

p_hat = rej.mean()
se_hat = np.sqrt(p_hat * (1 - p_hat) / m)
print(f"P value={p_hat}")
print(f"Standard error ={se_hat}")

#Checking for variance with chisquare
import numpy as np
from scipy import stats

n, alpha, sigma0_sq, m = 20, 0.05, 4, 10000
rej = np.empty(m)

for j in range(m):
    x = np.random.chisquare(df=2,size=n)
    V = (n - 1) * x.var(ddof=1) / sigma0_sq
    rej[j] = V > stats.chi2.ppf(1 - alpha, df=n - 1)

p_hat = rej.mean()
se_hat = np.sqrt(p_hat * (1 - p_hat) / m)
print(f"P value={p_hat}")
print(f"Standard error ={se_hat}")

#The Count Five Test:
import numpy as np
import matplotlib.pyplot as plt

def count5(x, y):
    X, Y = x - x.mean(), y - y.mean()
    outx = np.sum(X > Y.max()) + np.sum(X < Y.min())
    outy = np.sum(Y > X.max()) + np.sum(Y < X.min())
    return max(outx, outy)

n1, n2, m = 15, 18, 10000
T_obs = 12

null_stats = np.empty(m, dtype=int)
for j in range(m):
    x = np.random.normal(0, 1, n1)
    y = np.random.normal(0, 1, n2)
    null_stats[j] = count5(x, y)

# --- plot ---
bins = np.arange(null_stats.min(), null_stats.max() + 2) - 0.5
weights = np.ones_like(null_stats) / m

fig, ax = plt.subplots(figsize=(7, 5))
ax.hist(null_stats, bins=bins, weights=weights, color="blue", edgecolor="white")
ax.axvline(T_obs, color="black", linestyle="--", linewidth=1.5)
ax.text(T_obs - 0.3, ax.get_ylim()[1]*0.9, r"$T_{obs}=12$", ha="right")

ax.set_xlabel("T (Count Five statistic)")
ax.set_ylabel("proportion")
plt.tight_layout()
plt.show()