# -*- coding: utf-8 -*-
"""Monte carlo Integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDAdmWI4xqRJgTdeHcb5R0k1chfhDIg_
"""

#Integral e^-x
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1)
n=10000
U=np.random.uniform(0,1,n)
estimates=np.exp(-U)
I_hat=np.mean(estimates)
true_val=1-np.exp(-1)
print("Monte Carlo estimate:", I_hat)
print("True Value:",true_val)
running_avg=np.cumsum(estimates)/np.arange(1,n+1)
plt.plot(running_avg)
plt.xlabel("Number of Samples")
plt.ylabel("Running Average")
plt.show()

#Rayleigh density
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1)
sigma=1.0
n=10000
def mc_rayleigh_cdf(x,sigma,n):
  U=np.random.uniform(0,1,n)
  g=(x**2 * U / sigma**2) * np.exp(-(x * U)**2 / (2 * sigma**2))
  return np.mean(g)
def true_rayleigh_cdf(x,sigma):
  return 1-np.exp(-x**2/2/sigma**2)
x_vals=np.linspace(0.1,20,200)
mc_estimates=[mc_rayleigh_cdf(x,sigma,n) for x in x_vals]
true_estimates=[true_rayleigh_cdf(x,sigma) for x in x_vals]
print("Monte Carlo Estimates:",mc_estimates)
print("True Estimates:",true_estimates)
plt.plot(x_vals,mc_estimates,label="Monte Carlo Estimates",color='red')
plt.plot(x_vals,true_estimates,label="True Estimates")
plt.xlabel("x")
plt.ylabel("CDF(x)")
plt.legend()
plt.show()

