# -*- coding: utf-8 -*-
"""Pseudorandom number generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gK4TKWviJGAFTYQK467ZJXk7h8h9uHIi
"""

#1: Linear congruential generator
def lcg(seed, a, c, m):
    x=seed
    results=[]
    for _ in range(n):
      x=(a*x+c)%m
      results.append(x/m)
    return results
#Some example parameters
seed=1
a=1664525
c = 1013904223
m = 2**32
n = 10000
samples=lcg(seed, a, c, m)
print("First 20 values:\n")
for val in samples[:20]:
  print(val)

#Mixed Congruential Generators
def mixed_congruential(seed,a,c,m,n):
  x=seed
  results=[]
  for _ in range(n):
    x=(a*x+c)%m
    results.append(x/m)
  return results
#Example parameters
seed=1
a=1664525
c = 1013904223
m = 2**32
n = 10000

samples = mixed_congruential(seed, a, c, m, n)

for val in samples[:20]:
    print(val)