# -*- coding: utf-8 -*-
"""The Acceptance Rejection Method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcvsYAgZPThTvyK0-rsLQbzg9YuvYfSQ
"""

#Beta (3,2)
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta
from scipy.optimize import minimize_scalar
np.random.seed(1)
def rbeta_rejection(n,a,b):
  neg_pdf = lambda x: -beta.pdf(x,a,b)
  res=minimize_scalar(neg_pdf,bounds=(1e-6,1-1e-6),method='bounded')
  c=-res.fun
  samples=[]
  while len(samples)<n:
    y=np.random.uniform(0,1)
    U=np.random.uniform(0,1)
    if U<=beta.pdf(y,a,b)/c:
      samples.append(y)
  return np.array(samples)
a,b=3,2
n=1000
x=rbeta_rejection(n,a,b)
plt.hist(x,bins=40,density=True, label="Simulated")
xs=np.linspace(0,1,400)
plt.plot(xs,beta.pdf(xs,a,b),color="red",label="Theoretical")
plt.title("Simulated vs Theoretical")
plt.xlabel("x")
plt.ylabel("Density")
plt.legend()
plt.show()

#Gamma (1.5,1)
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import gamma, expon
from scipy.optimize import minimize_scalar

np.random.seed(1)

def rgamma_rejection(n, a, rate=1.0):
    def c_given_lam(lam):
        neg_ratio = lambda x: -(gamma.pdf(x, a, scale=1/rate) / expon.pdf(x, scale=1/lam))
        res = minimize_scalar(neg_ratio, bounds=(1e-6, 200), method='bounded')
        return -res.fun

    res_lam = minimize_scalar(c_given_lam, bounds=(1e-3, rate - 1e-3), method='bounded')
    lam = res_lam.x
    c = c_given_lam(lam)

    samples = []
    while len(samples) < n:
        y = np.random.exponential(scale=1/lam)
        u = np.random.uniform(0, 1)
        if u <= gamma.pdf(y, a, scale=1/rate) / (c * expon.pdf(y, scale=1/lam)):
            samples.append(y)

    return np.array(samples), lam, c

a, rate = 1.5, 1.0
n = 1000

x, lam, c = rgamma_rejection(n, a, rate)

plt.hist(x, bins=40, density=True, label="Simulated")

xs = np.linspace(0, x.max(), 400)
plt.plot(xs, gamma.pdf(xs, a, scale=1/rate), color="red", lw=2, label=f"Theoretical Gamma({a},{rate})")

plt.title(f"Simulated vs Theoretical Gamma")
plt.xlabel("x")
plt.ylabel("Density")
plt.legend()
plt.show()