# -*- coding: utf-8 -*-
"""The inverse transform method (continuous and discrete).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vP3_ebws9ETs5Yej3d4JRKWKgdt2pOHh
"""

#Standard Laplace
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import laplace
np.random.seed(1)
n=1000
U=np.random.uniform(0,1,n)
x=np.where(U<0.5,np.log(2*U),-np.log(2*(1-U)))
print ("Sample mean:",np.mean(x),"Theoretical mean =0")
print ("Sample variance:",np.var(x),"Theoretical variance =2")

plt.plot(xs,laplace.pdf(xs),label="Theoretical")
plt.hist(x,bins=40,density=True,label="Simulated")
plt.title("Histogram vs theoretical density")
plt.xlabel("x")
plt.ylabel("Density")
plt.legend()
plt.show()

#Weibull distribution
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import weibull_min

np.random.seed(1)
n = 1000
k = 2
lam = 1

U = np.random.uniform(0, 1, n)
x = lam * (-np.log(1 - U)) ** (1 / k)

xs = np.linspace(0, x.max(), 400)

plt.hist(x, bins=40, density=True, label="Simulated")
plt.plot(xs, weibull_min.pdf(xs, k, scale=lam), label="Theoretical")
plt.title("Histogram vs theoretical density")
plt.xlabel("x")
plt.ylabel("Density")
plt.legend()
plt.show()

#Pareto distribution
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pareto

np.random.seed(1)
n = 1000
b = 2
a = 2

U = np.random.uniform(0, 1, n)
x = b*((1-U)**(-1/a))

xs = np.linspace(0, x.max(), 400)

plt.hist(x, bins=40, density=True, label="Simulated")
plt.plot(xs, pareto.pdf(xs, a, scale=b), label="Theoretical")
plt.title("Histogram vs theoretical density")
plt.xlabel("x")
plt.ylabel("Density")
plt.legend()
plt.show()

#Binomial
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom

np.random.seed(1)
n_trials=30
p = 0.3
nsim=1000
k_vals=np.arange(0,n_trials+1)
cdf_vals=binom.cdf(k_vals,n_trials,p) #cumulative probs
U=np.random.uniform(0,1,nsim)
x=k_vals[np.searchsorted(cdf_vals,U)]
values,counts=np.unique(x,return_counts=True)
props=counts/nsim
plt.bar(values,props,label="Simulated")
plt.plot(k_vals,binom.pmf(k_vals,n_trials,p),label="Theoretical",color="red")
plt.title("Histogram vs theoretical density")
plt.xlabel("k")
plt.ylabel("Density")
plt.legend()
plt.show()